use std::{borrow::Borrow, sync::Arc};

use parking_lot::{Mutex, MutexGuard, RwLock, RwLockReadGuard, RwLockWriteGuard};

use crate::{ExclusiveKey, Key, ParentLock, ParentMarker};

/// A parent lock that uses a `parking_lot` [`Mutex`] to synchronize
/// access to child locks.
#[derive(Default)]
pub struct MutexParent {
    mutex: Mutex<()>,
    marker: ParentMarker,
}

impl ParentLock for MutexParent {
    fn marker(&self) -> &ParentMarker {
        &self.marker
    }
}

impl Borrow<dyn ParentLock> for MutexParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        self
    }
}

impl Borrow<dyn ParentLock> for &'_ MutexParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        *self
    }
}

impl Borrow<dyn ParentLock> for Arc<MutexParent> {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        &**self
    }
}

impl MutexParent {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            mutex: Mutex::new(()),
            marker: ParentMarker,
        }
    }

    /// Gets an exclusive key for this lock family, potentially blocking
    /// until it can be acquired.
    pub fn key(&self) -> MutexKey<'_> {
        MutexKey {
            guard: self.mutex.lock(),
            address: &self.marker,
        }
    }

    /// Tries to get an exclusive key for this lock family, without blocking.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is currently locked by another thread.
    pub fn try_key(&self) -> Option<MutexKey<'_>> {
        Some(MutexKey {
            guard: self.mutex.try_lock()?,
            address: &self.marker,
        })
    }
}

/// The key type generated by [`Mutexes`][Mutex].
#[expect(
    dead_code,
    reason = "The read guard is never used but it must be kept alive"
)]
pub struct MutexKey<'a> {
    guard: MutexGuard<'a, ()>,
    address: &'a ParentMarker,
}

// SAFETY: MutexKey contains a MutexGuard, which guaranatees that
// only one MutexKey can exist for a given MutexParent at a time.
unsafe impl Key for MutexKey<'_> {
    fn parent_marker(&self) -> &ParentMarker {
        self.address
    }
}

// SAFETY: MutexKey contains a MutexGuard, which guaranatees that
// only one MutexKey can exist for a given MutexParent at a time.
unsafe impl ExclusiveKey for MutexKey<'_> {}

/// A parent lock that uses a `parking_lot` [`RwLock`] to provide read/write access to child locks.
///
/// # You probably only need a [`MutexParent`].
///
/// See [`RwParent (std)`][crate::std::RwParent] for an explanation.
#[derive(Default)]
pub struct RwParent {
    lock: RwLock<()>,
    marker: ParentMarker,
}

impl ParentLock for RwParent {
    fn marker(&self) -> &ParentMarker {
        &self.marker
    }
}

impl Borrow<dyn ParentLock> for RwParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        self
    }
}

impl Borrow<dyn ParentLock> for &'_ RwParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        *self
    }
}

impl Borrow<dyn ParentLock> for Arc<RwParent> {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        &**self
    }
}

impl RwParent {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            lock: RwLock::new(()),
            marker: ParentMarker,
        }
    }

    /// Gets a shared key for this lock family, potentially blocking
    /// until it can be acquired. Will not block if another shared key
    /// already exists.
    pub fn shared_key(&self) -> RwLockReadKey<'_> {
        RwLockReadKey {
            guard: self.lock.read(),
            address: &self.marker,
        }
    }

    /// Tries to get a shared key for this lock family, without blocking.
    ///
    /// # Errors
    ///
    /// Returns an error if an exclusive key is currently held by another thread.
    pub fn try_shared_key(&self) -> Option<RwLockReadKey<'_>> {
        Some(RwLockReadKey {
            guard: self.lock.try_read()?,
            address: &self.marker,
        })
    }

    /// Gets an exclusive key for this lock family, potentially blocking
    /// until it can be acquired.
    pub fn exclusive_key(&self) -> RwLockWriteKey<'_> {
        RwLockWriteKey {
            guard: self.lock.write(),
            address: &self.marker,
        }
    }

    /// Tries to get an exclusive key for this lock family, without blocking.
    ///
    /// # Errors
    ///
    /// Returns an error if any key is currently held by another thread.
    pub fn try_exclusive_key(&self) -> Option<RwLockWriteKey<'_>> {
        Some(RwLockWriteKey {
            guard: self.lock.try_write()?,
            address: &self.marker,
        })
    }
}

/// A key type generated by [`RwLocks`][RwLock] that can only be used to read children.
///
/// Many of these keys can exist simultaneously, and each of them can be used to read
/// multiple children at once. A read key can't coexist with a write key.
#[expect(
    dead_code,
    reason = "The read guard is never used but it must be kept alive"
)]
pub struct RwLockReadKey<'a> {
    guard: RwLockReadGuard<'a, ()>,
    address: &'a ParentMarker,
}

// SAFETY: RwLockReadKey contains an RwLockReadGuard, which guarantees that this can't
// coexist with a write key.
unsafe impl Key for RwLockReadKey<'_> {
    fn parent_marker(&self) -> &ParentMarker {
        self.address
    }
}

/// A key type generated by [`RwLocks`][RwLock] that can be used to read and write children.
///
/// A write key can't coexist with a read key or other write keys, but can be used to read
/// multiple children at once.
#[expect(
    dead_code,
    reason = "The write guard is never used but it must be kept alive"
)]
pub struct RwLockWriteKey<'a> {
    guard: RwLockWriteGuard<'a, ()>,
    address: &'a ParentMarker,
}

// SAFETY: RwLockWriteKey contains an RwLockWriteGuard, which guarantees that this can't
// coexist with any other keys for this parent.
unsafe impl Key for RwLockWriteKey<'_> {
    fn parent_marker(&self) -> &ParentMarker {
        self.address
    }
}

// SAFETY: RwLockWriteKey contains an RwLockWriteGuard, which guarantees that this can't
// coexist with any other keys for this parent.
unsafe impl ExclusiveKey for RwLockWriteKey<'_> {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ChildLock;

    #[test]
    fn owned_child_mutex() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);

        let mut key = parent.key();
        assert_eq!(*mutex.write(&mut key), 5)
    }

    #[test]
    fn read_ref_child_mutex() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);

        let key = parent.key();
        assert_eq!(*mutex.read(&key), 5);
    }

    #[test]
    fn read_arc_child_mutex() {
        let parent = Arc::new(MutexParent::new());
        let mutex = ChildLock::new(5, parent.clone());

        let key = parent.key();
        assert_eq!(*mutex.read(&key), 5);
    }

    #[test]
    fn new_sibling_ref() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let sibling = mutex.new_sibling(10);

        let key = parent.key();

        assert_eq!(*mutex.read(&key), 5);
        assert_eq!(*sibling.read(&key), 10);
    }

    #[test]
    fn new_sibling_arc() {
        let parent = Arc::new(MutexParent::new());
        let mutex = ChildLock::new(5, parent.clone());

        drop(parent);

        let sibling = mutex.new_sibling(10);

        let key = mutex.parent.key();

        assert_eq!(*mutex.read(&key), 5);
        assert_eq!(*sibling.read(&key), 10);
    }

    #[test]
    fn write() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let mut key = parent.key();
        *mutex.write(&mut key) = 10;
        assert_eq!(*mutex.read(&key), 10);
    }

    #[test]
    #[should_panic]
    fn wrong_key_panic() {
        let parent = MutexParent::new();
        let impostor = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let key = impostor.key();
        assert_eq!(*mutex.read(&key), 5);
    }

    #[test]
    fn try_wrong_key_err() {
        let parent = MutexParent::new();
        let impostor = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let key = impostor.key();
        assert!(mutex.try_read(&key).is_err());
    }

    #[test]
    fn rw_parent() {
        let parent = RwParent::new();
        let child = ChildLock::new(5, &parent);

        let key1 = parent.shared_key();
        let key2 = child.parent.shared_key();

        assert_eq!(*child.read(&key1), 5);
        assert_eq!(*child.read(&key2), 5);
    }
}
