use std::{
    borrow::Borrow,
    sync::{
        Arc, LockResult, Mutex, MutexGuard, PoisonError, RwLock, RwLockReadGuard, RwLockWriteGuard,
        TryLockError, TryLockResult,
    },
};

use crate::{ExclusiveKey, Key, ParentLock, ParentMarker};

/// A parent lock that uses a [`Mutex`] to synchronize access to child locks.
///
/// Much like a [`Mutex`], this lock can become poisoned if a thread panics while
/// holding the key. See [`Mutex`] for more information.
#[derive(Default)]
pub struct MutexParent {
    mutex: Mutex<()>,
    marker: ParentMarker,
}

impl ParentLock for MutexParent {
    fn marker(&self) -> &ParentMarker {
        &self.marker
    }
}

impl Borrow<dyn ParentLock> for MutexParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        self
    }
}

impl Borrow<dyn ParentLock> for &'_ MutexParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        *self
    }
}

impl Borrow<dyn ParentLock> for Arc<MutexParent> {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        &**self
    }
}

impl MutexParent {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            mutex: Mutex::new(()),
            marker: ParentMarker,
        }
    }

    /// Gets an exclusive key for this lock family, potentially blocking
    /// until it can be acquired.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is poisoned. This happens when a thread
    /// panics while holding the key, which may leave the child lock contents
    /// in a state that doesn't uphold the lock's invariants. See [`Mutex`]
    /// for more information.
    pub fn key(&self) -> LockResult<MutexKey<'_>> {
        match self.mutex.lock() {
            Ok(guard) => Ok(MutexKey {
                guard,
                address: &self.marker,
            }),
            Err(e) => Err(PoisonError::new(MutexKey {
                guard: e.into_inner(),
                address: &self.marker,
            })),
        }
    }

    /// Tries to get an exclusive key for this lock family, without blocking.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is poisoned. See [`key`][MutexParent::key].
    /// Also returns an error if the lock is currently locked by another thread.
    pub fn try_key(&self) -> TryLockResult<MutexKey<'_>> {
        match self.mutex.try_lock() {
            Ok(guard) => Ok(MutexKey {
                guard,
                address: &self.marker,
            }),
            Err(TryLockError::Poisoned(e)) => {
                Err(TryLockError::Poisoned(PoisonError::new(MutexKey {
                    guard: e.into_inner(),
                    address: &self.marker,
                })))
            }
            Err(TryLockError::WouldBlock) => Err(TryLockError::WouldBlock),
        }
    }

    /// Determines if the lock is poisoned.
    pub fn is_poisoned(&self) -> bool {
        self.mutex.is_poisoned()
    }

    /// Clears the poison flag on the lock, if it is poisoned.
    pub fn clear_poison(&self) {
        self.mutex.clear_poison();
    }
}

/// The key type generated by [`Mutexes`][Mutex].
#[expect(
    dead_code,
    reason = "The read guard is never used but it must be kept alive"
)]
pub struct MutexKey<'a> {
    guard: MutexGuard<'a, ()>,
    address: &'a ParentMarker,
}

// SAFETY: MutexKey contains a MutexGuard, which guaranatees that
// only one MutexKey can exist for a given MutexParent at a time.
unsafe impl Key for MutexKey<'_> {
    fn parent_marker(&self) -> &ParentMarker {
        self.address
    }
}

// SAFETY: MutexKey contains a MutexGuard, which guaranatees that
// only one MutexKey can exist for a given MutexParent at a time.
unsafe impl ExclusiveKey for MutexKey<'_> {}

/// A parent lock that uses [`RwLock`] to provide read/write access to child locks.
///
/// # You probably only need a [`MutexParent`].
///
/// The utility of a [`RwParent`] is much more niche than a normal [`RwLock`]. A
/// [`RwLock`] allows multiple simultaneous reader threads or only one writer thread;
/// a [`RwParent`] allows multiple simultaneous reader *keys*, or only one writer
/// *key*. For comparison, a [`MutexParent`] only allows one [`MutexKey`] at a time,
/// but that single key can be shared across threads. It can be used to read any
/// number of [`ChildLocks`][super::ChildLock] simultaneously, and those children can be read
/// by any number of threads that share the key simultaneously.
///
/// You should only need to use a [`RwParent`] if it is for some reason impractical
/// to share the reader keys between all threads that need them.
#[derive(Default)]
pub struct RwParent {
    lock: RwLock<()>,
    marker: ParentMarker,
}

impl ParentLock for RwParent {
    fn marker(&self) -> &ParentMarker {
        &self.marker
    }
}

impl Borrow<dyn ParentLock> for RwParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        self
    }
}

impl Borrow<dyn ParentLock> for &'_ RwParent {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        *self
    }
}

impl Borrow<dyn ParentLock> for Arc<RwParent> {
    fn borrow(&self) -> &(dyn ParentLock + 'static) {
        &**self
    }
}

impl RwParent {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            lock: RwLock::new(()),
            marker: ParentMarker,
        }
    }

    /// Gets a shared key for this lock family, potentially blocking
    /// until it can be acquired. Will not block if another shared key
    /// already exists.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is poisoned. This happens when a thread
    /// panics while holding the key, which may leave the child lock contents
    /// in a state that doesn't uphold the lock's invariants. See [`RwLock`]
    /// for more information.
    pub fn shared_key(&self) -> LockResult<RwLockReadKey<'_>> {
        match self.lock.read() {
            Ok(guard) => Ok(RwLockReadKey {
                guard,
                address: &self.marker,
            }),
            Err(e) => Err(PoisonError::new(RwLockReadKey {
                guard: e.into_inner(),
                address: &self.marker,
            })),
        }
    }

    /// Tries to get a shared key for this lock family, without blocking.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is poisoned. See [`shared_key`][RwParent::shared_key].
    /// Also returns an error if an exclusive key is currently held by another thread.
    pub fn try_shared_key(&self) -> TryLockResult<RwLockReadKey<'_>> {
        match self.lock.try_read() {
            Ok(guard) => Ok(RwLockReadKey {
                guard,
                address: &self.marker,
            }),
            Err(TryLockError::Poisoned(e)) => {
                Err(TryLockError::Poisoned(PoisonError::new(RwLockReadKey {
                    guard: e.into_inner(),
                    address: &self.marker,
                })))
            }
            Err(TryLockError::WouldBlock) => Err(TryLockError::WouldBlock),
        }
    }

    /// Gets an exclusive key for this lock family, potentially blocking
    /// until it can be acquired.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is poisoned. This happens when a thread
    /// panics while holding the key, which may leave the child lock contents
    /// in a state that doesn't uphold the lock's invariants. See [`RwLock`]
    /// for more information.
    pub fn exclusive_key(&self) -> LockResult<RwLockWriteKey<'_>> {
        match self.lock.write() {
            Ok(guard) => Ok(RwLockWriteKey {
                guard,
                address: &self.marker,
            }),
            Err(e) => Err(PoisonError::new(RwLockWriteKey {
                guard: e.into_inner(),
                address: &self.marker,
            })),
        }
    }

    /// Tries to get an exclusive key for this lock family, without blocking.
    ///
    /// # Errors
    ///
    /// Returns an error if the lock is poisoned. See [`exclusive_key`][RwParent::exclusive_key].
    /// Also returns an error if any key is currently held by another thread.
    pub fn try_exclusive_key(&self) -> TryLockResult<RwLockWriteKey<'_>> {
        match self.lock.try_write() {
            Ok(guard) => Ok(RwLockWriteKey {
                guard,
                address: &self.marker,
            }),
            Err(TryLockError::Poisoned(e)) => {
                Err(TryLockError::Poisoned(PoisonError::new(RwLockWriteKey {
                    guard: e.into_inner(),
                    address: &self.marker,
                })))
            }
            Err(TryLockError::WouldBlock) => Err(TryLockError::WouldBlock),
        }
    }

    /// Determines if the lock is poisoned.
    pub fn is_poisoned(&self) -> bool {
        self.lock.is_poisoned()
    }

    /// Clears the poison flag on the lock, if it is poisoned.
    pub fn clear_poison(&self) {
        self.lock.clear_poison();
    }
}

/// A key type generated by [`RwLocks`][RwLock] that can only be used to read children.
///
/// Many of these keys can exist simultaneously, and each of them can be used to read
/// multiple children at once. A read key can't coexist with a write key.
#[expect(
    dead_code,
    reason = "The read guard is never used but it must be kept alive"
)]
pub struct RwLockReadKey<'a> {
    guard: RwLockReadGuard<'a, ()>,
    address: &'a ParentMarker,
}

// SAFETY: RwLockReadKey contains an RwLockReadGuard, which guarantees that this can't
// coexist with a write key.
unsafe impl Key for RwLockReadKey<'_> {
    fn parent_marker(&self) -> &ParentMarker {
        self.address
    }
}

/// A key type generated by [`RwLocks`][RwLock] that can be used to read and write children.
///
/// A write key can't coexist with a read key or other write keys, but can be used to read
/// multiple children at once.
#[expect(
    dead_code,
    reason = "The write guard is never used but it must be kept alive"
)]
pub struct RwLockWriteKey<'a> {
    guard: RwLockWriteGuard<'a, ()>,
    address: &'a ParentMarker,
}

// SAFETY: RwLockWriteKey contains an RwLockWriteGuard, which guarantees that this can't
// coexist with any other keys for this parent.
unsafe impl Key for RwLockWriteKey<'_> {
    fn parent_marker(&self) -> &ParentMarker {
        self.address
    }
}

// SAFETY: RwLockWriteKey contains an RwLockWriteGuard, which guarantees that this can't
// coexist with any other keys for this parent.
unsafe impl ExclusiveKey for RwLockWriteKey<'_> {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ChildLock;

    #[test]
    fn owned_child_mutex() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);

        let mut key = parent.key().unwrap();
        assert_eq!(*mutex.write(&mut key), 5)
    }

    #[test]
    fn read_ref_child_mutex() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);

        let key = parent.key().unwrap();
        assert_eq!(*mutex.read(&key), 5);
    }

    #[test]
    fn read_arc_child_mutex() {
        let parent = Arc::new(MutexParent::new());
        let mutex = ChildLock::new(5, parent.clone());

        let key = parent.key().unwrap();
        assert_eq!(*mutex.read(&key), 5);
    }

    #[test]
    fn new_sibling_ref() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let sibling = mutex.new_sibling(10);

        let key = parent.key().unwrap();

        assert_eq!(*mutex.read(&key), 5);
        assert_eq!(*sibling.read(&key), 10);
    }

    #[test]
    fn new_sibling_arc() {
        let parent = Arc::new(MutexParent::new());
        let mutex = ChildLock::new(5, parent.clone());

        drop(parent);

        let sibling = mutex.new_sibling(10);

        let key = mutex.parent.key().unwrap();

        assert_eq!(*mutex.read(&key), 5);
        assert_eq!(*sibling.read(&key), 10);
    }

    #[test]
    fn write() {
        let parent = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let mut key = parent.key().unwrap();
        *mutex.write(&mut key) = 10;
        assert_eq!(*mutex.read(&key), 10);
    }

    #[test]
    #[should_panic]
    fn wrong_key_panic() {
        let parent = MutexParent::new();
        let impostor = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let key = impostor.key().unwrap();
        assert_eq!(*mutex.read(&key), 5);
    }

    #[test]
    fn try_wrong_key_err() {
        let parent = MutexParent::new();
        let impostor = MutexParent::new();
        let mutex = ChildLock::new(5, &parent);
        let key = impostor.key().unwrap();
        assert!(mutex.try_read(&key).is_err());
    }

    #[test]
    fn rw_parent() {
        let parent = RwParent::new();
        let child = ChildLock::new(5, &parent);

        let key1 = parent.shared_key().unwrap();
        let key2 = child.parent.shared_key().unwrap();

        assert_eq!(*child.read(&key1), 5);
        assert_eq!(*child.read(&key2), 5);
    }
}
